version: '3'
services:
  flutter_web:
    image: cirrusci/flutter:stable
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: bash -c "flutter config --enable-web && flutter pub get && flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8080"
    stdin_open: true
    tty: true